interiorselection/interiorselection/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('main.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

interiorselection/main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.mainpg, name='home'),
    path('home', views.mainpg, name='home'),
    path('contacts', views.about, name='contacts'),
    path('stock', views.ListInterior.as_view(), name='stock'),
    path('stock/<int:id>/', views.DetailInterior.as_view(), name='stock_detail'),
    path('stock/create', views.CreateInterior.as_view(), name='stock_create'),
    path('stock/<int:id>/update', views.UpdateInterior.as_view(), name='stock_update'),
    path('stock/<int:id>/delete', views.DeleteInterior.as_view(), name='stock_delete'),
    path('displacement', views.DisplacementView.as_view(), name='displacement'),
    path('cabinets', views.CabinetsView.as_view(), name='cabinets'),
    path('create_room', views.CreateRoomView.as_view(), name='create_room'),
    path('room/<int:id>/', views.RoomView.as_view(), name='room'),
    path('room/<int:id>/update', views.UpdateRoomView.as_view(), name='update_room'),
    path('room/<int:id>/delete', views.DeleteRoomView.as_view(), name='delete_room'),
]

interiorselection/main/models.py
from django.db import models
from PIL import Image


class Room(models.Model):

    name = models.CharField(unique=True, max_length=40)
    description = models.TextField(null=True, blank=True)
    image = models.ImageField(null=True, blank=True, upload_to='photos/')
    exist = models.BooleanField(default=True, blank=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if self.image:
            img = Image.open(self.image.path)
            if img.height > 200 or img.width > 200:
                middle = min(img.height, img.width)
                new_img = img.crop(
                    ((img.width - middle) // 2,
                     (img.height - middle) // 2,
                     img.width - (img.width - middle) // 2,
                     img.height - (img.height - middle) // 2))
                new_img = new_img.resize((200, 200))
                new_img.save(self.image.path)


class Interior(models.Model):

    name = models.CharField(max_length=50)
    description = models.TextField(null=True, blank=True)
    room = models.ForeignKey(to=Room, on_delete=models.DO_NOTHING)
    exist = models.BooleanField(default=True, blank=True)

    def __str__(self):
        return self.name + ' | ' + self.room.name


class Displacement(models.Model):

    object = models.ForeignKey(to=Interior, on_delete=models.DO_NOTHING)
    from_room = models.ForeignKey(to=Room, null=True, related_name='from_room', on_delete=models.DO_NOTHING)
    to_room = models.ForeignKey(to=Room, null=True, related_name='to_room', on_delete=models.DO_NOTHING)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.object.name + ' | ' + self.from_room.name + ' | ' + self.to_room.name + ' | ' + str(self.date)

interiorselection/main/forms.py
from .models import *
from django.forms import ModelForm, TextInput, Textarea, FileInput, Select


class RoomForm(ModelForm):

    class Meta:
        model = Room
        fields = ['name', 'description', 'image']
        widgets = {
            'name': TextInput(attrs={
                'class': 'form-control py-1',
            }),
            'description': Textarea(attrs={
                'class': 'form-control py-1',
                'cols': '40',
                'rows': '7'
            }),
            'image': FileInput(attrs={
                'class': 'form-control py-1',
            }),
        }


class InteriorForm(ModelForm):

    def __init__(self, *args, **kwargs):
        super(InteriorForm, self).__init__(*args, **kwargs)
        self.fields['room'].queryset = Room.objects.filter(exist=True)

    class Meta:
        model = Interior
        fields = ['name', 'description', 'room']
        widgets = {
            'name': TextInput(attrs={
                'class': 'form-control py-1',
            }),
            'description': Textarea(attrs={
                'class': 'form-control py-1',
                'cols': '40',
                'rows': '7'
            }),
            'room': Select(attrs={
                'class': 'form-control py-1',
            }),
        }

interiorselection/main/views.py
from django.views import View
from django.views.generic import ListView, UpdateView, CreateView
from django.urls import reverse
from .forms import *
from .models import *
from django.shortcuts import render, redirect, get_object_or_404
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required


def about(request):
    return render(request, 'main/about.html')


def mainpg(request):
    return render(request, 'main/mainpg.html')


class CabinetsView(View):

    def post(self, request):
        id = request.POST.get('id')
        return redirect(reverse('room', kwargs={'id': id}))

    def get(self, request):
        rooms = Room.objects.exclude(exist=False)
        return render(request, 'main/cabinets.html', {'rooms': rooms})


class RoomView(View):

    def get(self, request, id):
        rooms = Room.objects.exclude(exist=False)
        room = get_object_or_404(rooms, id=id)
        interior = Interior.objects.filter(room_id=id, exist=True)
        return render(request, 'main/room.html', {'room': room, 'interior': interior})

    @method_decorator(login_required)
    def post(self, request, id):
        if request.POST.get('delete'):
            return redirect(reverse('delete_room', kwargs={'id': id}))
        if request.POST.get('update'):
            return redirect(reverse('update_room', kwargs={'id': id}))


class CreateRoomView(View):

    @method_decorator(login_required)
    def post(self, request):
        form = RoomForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('cabinets')
        else:
            error = 'Ошибка добавления записи'
            form = RoomForm()
            return render(request, 'main/create_room.html', {'form': form, 'error': error})

    @method_decorator(login_required)
    def get(self, request):
        form = RoomForm()
        error = ''
        return render(request, 'main/create_room.html', {'form': form, 'error': error})


class UpdateRoomView(View):

    @method_decorator(login_required)
    def post(self, request, id):
        room = get_object_or_404(Room, id=id)
        try:
            room.name = request.POST.get('name')
            room.description = request.POST.get('description')
            if request.FILES.get('image'):
                if room.image:
                    storage, path = room.image.storage, room.image.path
                    room.image = request.FILES.get('image')
                    storage.delete(path)
                else:
                    room.image = request.FILES.get('image')
            room.save()
            return redirect(reverse('room', kwargs={'id': id}))
        except:
            error = 'Ошибка редактирования комнаты'
            return render(request, 'main/update_room.html', {'room': room, 'error': error})

    @method_decorator(login_required)
    def get(self, request, id):
        rooms = Room.objects.exclude(exist=False)
        room = get_object_or_404(rooms, id=id)
        return render(request, 'main/update_room.html', {'room': room})


class DeleteRoomView(View):

    @method_decorator(login_required)
    def get(self, request, id):
        room = get_object_or_404(Room, id=id)
        if room.name == 'Склад':
            return redirect('cabinets')
        room.exist = False
        room.save()
        store, created = Room.objects.get_or_create(name='Склад', defaults={
            'description': 'Помещение для хранения предметов, непривязанных к комнате'})
        interior = Interior.objects.filter(room__id=id)
        for el in interior:
            el.room = store
            el.save()
            Displacement.objects.create(object=el, from_room=room, to_room=store)
        return redirect('cabinets')


class DisplacementView(View):

    @method_decorator(login_required)
    def post(self, request):
        id = request.POST.get('id')
        if id is None:
            displace = Displacement.objects.all()
        else:
            displace = Displacement.objects.filter(object__id=id)
        return render(request, 'main/displacement.html', {'displace': displace, 'id': id})

    @method_decorator(login_required)
    def get(self, request):
        id = None
        displace = Displacement.objects.all()
        return render(request, 'main/displacement.html', {'displace': displace, 'id': id})


class ListInterior(ListView):
    model = Interior
    template_name = 'main/stock.html'

    def get_queryset(self):
        return Interior.objects.filter(exist=True)


class DetailInterior(View):
    context = {}

    def get(self, request, id):
        interior = get_object_or_404(Interior, id=id, exist=True)
        self.context['object'] = interior
        self.context['displace'] = Displacement.objects.filter(object=interior)
        return render(request, 'main/detail_interior.html', self.context)

    @method_decorator(login_required)
    def post(self, request, id):
        if request.POST.get('delete'):
            return redirect(reverse('stock_delete', kwargs={'id': id}))
        if request.POST.get('update'):
            return redirect(reverse('stock_update', kwargs={'id': id}))


class UpdateInterior(UpdateView):
    model = Interior
    form_class = InteriorForm
    template_name = 'main/update_interior.html'
    pk_url_kwarg = 'id'

    def get_queryset(self):
        return super().get_queryset().filter(exist=True)

    def form_valid(self, form):
        self.object = form.save()
        displacement = Displacement.objects.filter(object=self.object).last()
        if self.object.room != displacement.to_room:
            displace = Displacement(object=self.object, from_room=displacement.to_room,
                                    to_room=self.object.room)
            displace.save()
        return redirect('stock_detail', self.kwargs['id'])


class CreateInterior(CreateView):
    model = Interior
    form_class = InteriorForm
    template_name = 'main/create_interior.html'
    pk_url_kwarg = 'id'

    def get_queryset(self):
        return super().get_queryset().filter(exist=True)

    def form_valid(self, form):
        self.object = form.save()
        displacement = Displacement(object=self.object, to_room=self.object.room)
        displacement.save()
        return redirect('stock')


class DeleteInterior(View):
    @method_decorator(login_required)
    def get(self, request, id):
        interior = get_object_or_404(Interior, id=id)
        interior.exist = False
        interior.save()
        return redirect('stock')

interiorselection/main/templates/main/about.html
{% extends 'main/base.html '%}

{% block title %}
Контакты
{% endblock %}
{% block links %}
                <li><a href="{% url 'home' %}" class="nav-link px-2 link-dark">Главная</a></li>
                <li><a href="{% url 'cabinets' %}" class="nav-link px-2 link-dark">Кабинеты</a></li>
                <li><a href="{% url 'stock' %}" class="nav-link px-2 link-dark">Инвентарь</a></li>
                <li><a href="{% url 'contacts' %}" class="nav-link px-2 link-secondary">Контакты</a></li>
{% endblock %}
{% block content %}
    <main>
        <section class="py-3 text-left container">
            <div class = "layer1">
                <div class="row-xl-auto py-lg-auto">
                    <div class=".col-xl-auto col-md-auto mx-3">
                        <h1 class="fw-dark">Это наша команда:</h1>
                        <p class="lead text-dark"> &nbsp; </p>
                        <div class="row g-6 mb-1 ">
                            <div class="col-md-6 ">
                                <div class="row g-2 border rounded overflow-hidden flex-md-row mb-4 shadow-sm position-relative h-100 w-100">
                                    <div class="col p-4 d-flex flex-column position-static">
                                        <strong class="d-inline-block mb-2 text-primary">BackEnd</strong>
                                        <h3 class="mb-2">Группа Бэкэндеров</h3>
                                        <div class="mb-3 text-muted">Студенты РТУ МИРЭА</div>
                                        <div class="container py-3">
                                            <hr class="dropdown-divider" >
                                            <div class="row text-center">
                                                <div class="col">
                                                    <a href="https://vk.com/id385925605" class="link-primary text-decoration-none">Александр Калинин</a>
                                                </div>
                                                <div class="col">
                                                    <a href="https://vk.com/id183354128" class="link-primary text-decoration-none">Владислав Ильин</a>
                                                </div>
                                                <div class="col">
                                                    <a href="https://vk.com/safina__alsu" class="link-primary text-decoration-none">Алсу Сафина</a>
                                                </div>
                                            </div>
                                            <hr class="dropdown-divider" >
                                        </div>
                                        <p class="card-text-center mb-auto"></p>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="row g-2 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-100 position-relative">
                                    <div class="col p-4 d-flex flex-column position-static">
                                        <strong class="d-inline-block mb-2 text-danger">FrontEnd</strong>
                                        <h3 class="mb-2">Группа Фронтендеров</h3>
                                        <div class="mb-3 text-muted">Студенты РТУ МИРЭА</div>
                                        <div class="container">
                                            <hr class="dropdown-divider" >
                                            <div class="row text-center">
                                                <div class="col">
                                                    <a href="https://vk.com/elenadubikova" class="link-danger text-decoration-none">Елена Дубикова</a>
                                                </div>
                                                <div class="col">
                                                    <a href="https://vk.com/evgenii_bashirov" class="link-danger text-decoration-none">Евгений Баширов</a>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="container">
                                            <hr class="dropdown-divider" >
                                            <div class="row text-center">
                                                <div class="col">
                                                    <a href="https://vk.com/id185823527" class="link-danger text-decoration-none">Владимир Шкред</a>
                                                </div>
                                                <div class="col">
                                                    <a href="https://vk.com/a.lunyakov" class="link-danger text-decoration-none">Алексей Луняков</a>
                                                </div>
                                            </div>
                                            <hr class="dropdown-divider">
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
            </div>
            <div class="layer2 py-xl-4">
                <div class="row-xl-auto py-lg-5">
                    <div class=".col-xl-auto col-md-auto mx-3 flex-md-row">
                        <h1 class="fw-dark">Главные преимущества проекта</h1>
                        <div class="row gx-6">
                            <div class = "layer_var">
                                <div class="col-md-auto text-center">
                                    <div class="row g-4 py-5 row-cols-lg-2">
                                        <div class="col">
                                            <div class="p-3 border rounded overflow-hidden shadow-sm bg-white h-100">
                                                <h4>Простота</h4>
                                                <p>Пользователь, не обладающий навыками программирования, может самостоятельно и быстро редактировать базу данных.</p>
                                            </div>
                                        </div>
                                        <div class="col">
                                            <div class="p-3 border rounded overflow-hidden shadow-sm bg-white h-100">
                                                <h4>Удобство</h4>
                                                <p>Удобный интерфейс позволяет избежать длительной адаптации к сайту.</p>
                                            </div>                                        </div>
                                        <div class="col">
                                            <div class="p-3 border rounded overflow-hidden shadow-sm bg-white h-100">
                                                <h4>Эластичность</h4>
                                                <p>В проекте использованы известные и достаточно простые технологии, что позволяет без проблем изменять его в случае необходимости.</p>
                                            </div>                                        </div>
                                        <div class="col">
                                            <div class="p-3 border rounded overflow-hidden shadow-sm bg-white h-100">
                                                <h4>Универсальность</h4>
                                                <p>Сайт можно использовать для любых структур, которые соответствуют отношению "контейнеры/элементы" или отношению "объекты/свойства".</p>
                                            </div>                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            </div>
        </section>
        <section class = "text-center container">
            <p>
                <a href="{% url 'home' %}" class="btn btn-outline-secondary my-2">На главную</a>
            </p>
        </section>

    </main>
{% endblock %}

interiorselection/main/templates/main/base.html
<!doctype html>
<html lang="ru">
<head>
<!--  Обязательные мета-теги  -->
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0"> <!--  user-scalable=no, maximum-scale=1.0, minimum-scale=1.0 пока убрал -->
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

<!--  CSS Bootstrap5 link -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<!--  Заголовок страницы  -->
    <title>{% block header_title %}{% endblock %}</title>

</head>
<body>
<!-- Контейнер -->
    <div class="container"> <!-- Ниже хэдер -->
        <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
            <a href="{% url 'home' %}" class="d-flex align-items-center col-md-3 mb-3 mb-md-0 text-dark text-decoration-none">
                <svg xmlns="http://www.w3.org/2000/svg" width="35" height="35" fill="currentColor" class="bi bi-gear-wide-connected" viewBox="0 0 16 16">
                    <path d="M7.068.727c.243-.97 1.62-.97 1.864 0l.071.286a.96.96 0 0 0 1.622.434l.205-.211c.695-.719 1.888-.03 1.613.931l-.08.284a.96.96 0 0 0 1.187 1.187l.283-.081c.96-.275 1.65.918.931 1.613l-.211.205a.96.96 0 0 0 .434 1.622l.286.071c.97.243.97 1.62 0 1.864l-.286.071a.96.96 0 0 0-.434 1.622l.211.205c.719.695.03 1.888-.931 1.613l-.284-.08a.96.96 0 0 0-1.187 1.187l.081.283c.275.96-.918 1.65-1.613.931l-.205-.211a.96.96 0 0 0-1.622.434l-.071.286c-.243.97-1.62.97-1.864 0l-.071-.286a.96.96 0 0 0-1.622-.434l-.205.211c-.695.719-1.888.03-1.613-.931l.08-.284a.96.96 0 0 0-1.186-1.187l-.284.081c-.96.275-1.65-.918-.931-1.613l.211-.205a.96.96 0 0 0-.434-1.622l-.286-.071c-.97-.243-.97-1.62 0-1.864l.286-.071a.96.96 0 0 0 .434-1.622l-.211-.205c-.719-.695-.03-1.888.931-1.613l.284.08a.96.96 0 0 0 1.187-1.186l-.081-.284c-.275-.96.918-1.65 1.613-.931l.205.211a.96.96 0 0 0 1.622-.434l.071-.286zM12.973 8.5H8.25l-2.834 3.779A4.998 4.998 0 0 0 12.973 8.5zm0-1a4.998 4.998 0 0 0-7.557-3.779l2.834 3.78h4.723zM5.048 3.967c-.03.021-.058.043-.087.065l.087-.065zm-.431.355A4.984 4.984 0 0 0 3.002 8c0 1.455.622 2.765 1.615 3.678L7.375 8 4.617 4.322zm.344 7.646.087.065-.087-.065z"/>
                </svg>
            </a>
            <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0"> <!-- Навигация по сайту -->
                {% block links %}{% endblock %}
            </ul>
            <div class="col-md-3 text-end"> <!-- Логинка  -->
                {% if user.is_authenticated %}
                    <div class = "badge border border-outline border-2 text-wrap text-dark">
                        <h6 class="text-center">Hi {{ user.username }}!</h6>
                    </div>
                    <a href="{% url 'logout' %}" class="btn btn-outline-danger">Выйти</a>
                {% else %}
                    <a href="{% url 'signup' %}" class="btn btn-primary">Регистрация</a>
                    <a href="{% url 'login' %}" class="btn btn-outline-primary me-2">Войти</a>
                {% endif %}
            </div>
        </header>
    </div>
    {% block content %}{% endblock %}
    <div class="container"> <!-- Футер -->
        <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
            <div class="col-md-4 d-flex align-items-center">
                <span class="text-black-50">© 2022 ИКБО-05-21, РТУ МИРЭА</span>
            </div>
        </footer>
    </div>
    <!-- Ссылка на скрипты -->
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script></body>
</html>

interiorselection/main/templates/main/create_room.html
{% extends 'main/base.html '%}

{% block title %}
Страница для добавления кабинета
{% endblock %}
{% block links %}
                <li><a href="{% url 'home' %}" class="nav-link px-2 link-dark">Главная</a></li>
                <li><a href="{% url 'cabinets' %}" class="nav-link px-2 link-secondary">Кабинеты</a></li>
                <li><a href="{% url 'stock' %}" class="nav-link px-2 link-dark">Инвентарь</a></li>
                <li><a href="{% url 'contacts' %}" class="nav-link px-2 link-dark">Контакты</a></li>
{% endblock %}
{% block content %}
    <main>
        <section class="py-5 text-center container">
            <div class="row py-lg-6">
                <div class="col-lg-6 col-md-8 mx-auto">
                    <h1 class="fw-dark">Добавить комнату</h1>
                </div>
                <form enctype="multipart/form-data" method="post">
                    {% csrf_token %}
                    <div class="container py-lg-3">
                        <div class="row md-6">
                            <div class="col-md-6 p-2 py-4 offset-md-3 border border-2 rounded shadow-sm row justify-content-center">
                                <div class="col-md-8">
                                    <div class="form-group m-2">
                                        <label for="id_name" class="py-1">Название комнаты:</label>
                                        {{ form.name }}
                                        <small class="form-text text-muted">Поле названия комнаты должно быть заполненно</small>
                                    </div>
                                    <div class="form-group m-2" >
                                        <label class="py-2">Описание:</label>
                                        {{ form.description }}
                                    </div>
                                    <div class="form-group m-2 py-1">
                                        <label class="py-2">Фотография:</label>
                                        {{ form.image }}
                                    </div>
                                    <button class="btn btn-primary my-3" type="sumbit">Добавить комнату</button>
                                    <p>{{error}}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
                <p class="py-3">
                    <a href="{% url 'home' %}" class="btn btn-outline-secondary my-2">На главную</a>
                </p>
            </div>
        </section>
    </main>
{% endblock %}

interiorselection/main/templates/main/update_room.html
{% extends 'main/base.html '%}

{% block title %}
Страница для добавления кабинета
{% endblock %}
{% block links %}
                <li><a href="{% url 'home' %}" class="nav-link px-2 link-dark">Главная</a></li>
                <li><a href="{% url 'cabinets' %}" class="nav-link px-2 link-secondary">Кабинеты</a></li>
                <li><a href="{% url 'stock' %}" class="nav-link px-2 link-dark">Инвентарь</a></li>
                <li><a href="{% url 'contacts' %}" class="nav-link px-2 link-dark">Контакты</a></li>
{% endblock %}
{% block content %}
    <main>
        <section class="py-5 text-center container">
            <div class="row py-lg-6">
                <div class="col-lg-6 col-md-8 mx-auto">
                    <h1 class="fw-dark">Изменить комнату</h1>
                </div>
                <form enctype="multipart/form-data" method="post">
                    {% csrf_token %}
                    <div class="container py-lg-3">
                        <div class="col-md-6 p-2 py-4 offset-md-3 border border-2 rounded shadow-sm row justify-content-center">
                            <div class="col-md-8">
                                <div class="form-group m-2">
                                    <label for="id_name">Название комнаты:</label>
                                    <input type="text" class="form-control" id="id_name" aria-describedby="nameHelp" name="name" value="{{room.name}}" maxlength="40" required="">
                                    <small id="nameHelp" class="form-text text-muted">Поле названия комнаты должно быть заполнено</small>
                                </div>
                                <div class="form-group m-2" >
                                    <label for="id_description">Описание:</label>
                                    <textarea class="form-control" id="id_description" name="description" cols="40" rows="7">{{room.description}}</textarea>
                                </div>
                                <div class="form-group m-2">
                                    {% if room.image %}
                                        <label for="id_image">Фотография</label>
                                        <img src="{{room.image.url}}">
                                    {% else %}
                                        <p class="file-upload">На данный момент фотографии нет</p>
                                    {% endif %}
                                        <input id="id_image" type="file" class="form-control-file" name="image" accept="image/*">
                                </div>
                                <button class="btn btn-primary my-3" type="sumbit">Сохранить</button>
                                <p>{{error}}</p>
                            </div>
                        </div>
                    </div>

                </form>
                <p class="py-3">
                    <a href="{% url 'home' %}" class="btn btn-outline-secondary my-2">На главную</a>
                </p>
            </div>
        </section>
    </main>
{% endblock %}